```{r}
# Load necessary libraries
library(maftools)
library(readr)
library(dplyr)
library(UpSetR)

# Step 1: Read the CSV files
paths = list(
    '/Users/famke/01-ghga-project/homogeneous-data-processing/variantcalling/TCGA-CHOL/sarek_strelka_samples.csv',
    '/Users/famke/01-ghga-project/homogeneous-data-processing/variantcalling/TCGA-CHOL/sarek_mutect_samples.csv',
    '/Users/famke/01-ghga-project/homogeneous-data-processing/variantcalling/TCGA-CHOL/tcga_mutect_samples.csv',
    '/Users/famke/01-ghga-project/homogeneous-data-processing/variantcalling/TCGA-CHOL/tcga_pindel_samples.csv',
    '/Users/famke/01-ghga-project/homogeneous-data-processing/variantcalling/TCGA-CHOL/tcga_varscan_samples.csv',
    '/Users/famke/01-ghga-project/homogeneous-data-processing/variantcalling/TCGA-CHOL/tcga_muse_samples.csv'
    )
```
```{r}
# Step 2: Define a function to read MAF files from CSV column filepath
read_mafs <- function(csv_file) {
    maf_files <- read_csv(csv_file)$filepath
    mafs <- lapply(as.list(maf_files), maftools::read.maf)
    merged_mafs <-  maftools::merge_mafs(mafs)
    return(merged_mafs)
}
```
```{r}
all_mafs <- llply(paths, read_mafs)
print(all_mafs)
```
```{r}
variant_list <- llply(all_mafs, function(maf) maf@data$Hugo_Symbol) # Hugo_Symbol = Gene Name

# Name the columns of the matrix
names(variant_list) <- c(
    "Sarek Strelka",
    "Sarek Mutect",
    "TCGA MuTect2", 
    "TCGA Pindel", 
    "TCGA VarScan", 
    "TCGA MuSE" 
    )

png(file = "comparison/results/upset-all.png", width=600, height=700)
upset_plot <- UpSetR::upset(fromList(variant_list), 
                            order.by = "freq",
                            main.bar.color = "skyblue",
                            matrix.color = "skyblue",
                            text.scale = 1.5,
                            point.size = 3,
                            )
print(upset_plot)
dev.off()
```
```{r}
# Define the order of the sets
set_order <- c(    
    "Sarek Strelka",
    "Sarek Mutect",
    "TCGA MuTect2", 
    "TCGA Pindel", 
    "TCGA VarScan", 
    "TCGA MuSE"
    )
```
```{r}
# Create a list to store the top 10 mutated genes per set
top_genes_per_set <- list()

# Iterate over each set in variant_list
for (set_name in set_order) {
  # Get the variants for the current set
  variants <- variant_list[[set_name]]
  
  # Count the frequency of each gene
  gene_counts <- table(variants)
  
  # Sort the genes by frequency in descending order
  sorted_genes <- sort(gene_counts, decreasing = TRUE)
  
  # Get the top 10 mutated genes
  top_genes <- names(sorted_genes)[1:10]
  
  # Store the top genes in the list
  top_genes_per_set[[set_name]] <- top_genes
}

# Create a data frame to store the top mutated genes
top_genes_df <- data.frame(matrix(ncol = length(set_order), nrow = 10))
colnames(top_genes_df) <- set_order

# Add frequency to the gene names in the data frame
for (i in 1:length(set_order)) {
  # Get the set name
  set_name <- set_order[i]
  
  # Get the top mutated genes for the current set
  top_genes <- top_genes_per_set[[set_name]]
  
  # Get the gene counts for the current set
  gene_counts <- table(variant_list[[set_name]])
  
  # Add frequency to the gene names
  top_genes_with_frequency <- paste(top_genes, " [", gene_counts[top_genes], "]", sep = "")
  
  # Assign the top genes with frequency to the corresponding column in the data frame
  top_genes_df[, i] <- top_genes_with_frequency
}

# Export the data frame as a CSV file
write.csv(top_genes_df, file = "comparison/results/top_mutated_genes.csv", row.names = FALSE)
```